APP_TITLE = "Levli Beta 1"
APP_SUBTITLE = "Fundamental Quality Filter — 30-stock working test"
FMP_BASE_URL = "https://financialmodelingprep.com/stable"

MIN_QUICK_RATIO = 1.0
MIN_ROE = 12.0
MIN_ROIC = 9.0
MIN_GROSS_MARGIN = 38.0
MIN_PROFIT_MARGIN = 7.0

EXCELLENT_ROE = 30.0
EXCELLENT_GROSS_MARGIN = 45.0
EXCELLENT_PROFIT_MARGIN = 20.0
CHEAP_PS = 2.0
REASONABLE_PS = 8.0
